### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by Mainframe2008** [elastic/sense#111]
We get the following error when we installed a self signed certificate:

Error connecting to 'https://server.mydomain.tld:9200/_search' :

Client request error: self signed certificate in certificate chain

Kibana 4.4.0
ES: 2.2.0
Shield 2.2.0
Sense 2.0.0-beta2

**Comment by vicvega** [comment]
Maybe related to https://github.com/elastic/sense/issues/69

**Comment by Mainframe2008** [comment]
It is. The supplied temp fix helped out.

**Comment by spalger** [comment]
duplicate of https://github.com/elastic/sense/issues/69
