### ISSUE TITLE
Sense via command line

### ISSUE THREAD

**Issue by thesmart** [elastic/sense#118]
It would be great to be able to run ElasticSearch requests written in Sense's syntax, but from the command line using standard input.  Is there already a binary for this?  Would others find this useful?

**Comment by spalger** [comment]
That is currently what the "copy as curl" functionality is defined to allow. The fact that you can then paste the curl commands back into sense and it will parse the curl into sense syntax sort-of helps this workflow.

**Comment by clintongormley** [comment]
@thesmart it does have it. just highlight all the commands you want to copy-as-curl
