### ISSUE TITLE
Incorrect HTTP verb gives a misleading error

### ISSUE THREAD

**Issue by jsvd** [elastic/sense#138]
this happened on sense 2.0.0-beta5:

![image](https://cloud.githubusercontent.com/assets/31809/15141132/e0da1fc4-169e-11e6-8ffc-84bf8be2d44f.png)

Because instead of "GET" I had a typo "lGET", sense gives you:

```
Failed to connect to Sense's backend.
Please check the Kibana server is up and running
```

**Comment by spalger** [comment]
Yeah, this isn't great. Mind moving the issue over to elastic/kibana though? Sense is now console in kibana.

**Comment by jsvd** [comment]
migrated to https://github.com/elastic/kibana/issues/7162
