### ISSUE TITLE
error while installing sense

### ISSUE THREAD

**Issue by shr269** [elastic/sense#141]
i have downloaded kibana from the official elastic product page. Trying to install sense. Getting the below error. what to do?

C:\DEV\kibana\bin>kibana plugin --install elastic/sense
Installing sense
Attempting to transfer from https://download.elastic.co/elastic/sense/sense-latest.tar.gz
Error: Client request error: connect ETIMEDOUT 184.73.171.50:443
Plugin installation was unsuccessful due to error "Client request error: connect ETIMEDOUT 184.73.171.50:443"

FYI: I am using a Windows machine

**Comment by clintongormley** [comment]
This was probably a temporary glitch - works fine for me now
