### ISSUE TITLE
error while installing marvel

### ISSUE THREAD

**Issue by shr269** [elastic/sense#142]
I have downloaded elastic search. Trying to download marvel. Finding the below error.
what to do?

C:\DEV\elasticsearch\bin>plugin install elasticsearch/marvel/latest
-> Installing elasticsearch/marvel/latest...
Trying https://download.elastic.co/elasticsearch/marvel/marvel-latest.zip ...
Trying https://search.maven.org/remotecontent?filepath=elasticsearch/marvel/latest/marvel-latest.zip ...
Tryinghttps://oss.sonatype.org/service/local/repositories/releases/content/elasticsearch/marvel/latest/marvel-latest.zip ...
Trying https://github.com/elasticsearch/marvel/archive/latest.zip ...
Trying https://github.com/elasticsearch/marvel/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

FYI: i am using windows machine

**Comment by clintongormley** [comment]
You don't mention which version of Elasticsearch you're using, but you probably want:

    ./bin/plugin install marvel-agent
