### ISSUE TITLE
Install sense on kibana v5.0.2

### ISSUE THREAD

**Issue by farhan687** [elastic/sense#160]
Hey, 
I have installed kibana v5.0.2 and elasticsearch v5.0 and both are working fine but how can I install the sense plugin?

I have tried following ways to install sense but nothing works.

1) kibana plugin --install elastic/sense
2) kibana-plugin install elastic/sense
3) kibana-plugin install https://github.com/elastic/sense.git

I am using windows machine.

**Comment by johtani** [comment]
Hi @farhan687 ,
"Sense is now included as Console in Kibana 5.0." 
Please read [README.md](https://github.com/elastic/sense) and [Kibana doc](https://www.elastic.co/guide/en/kibana/current/console-kibana.html)
