### ISSUE TITLE
Installing sense on Kibana 5.1.1 on Windows gives: No valid url specified

### ISSUE THREAD

**Issue by ashrav** [elastic/sense#162]
I'm using Windows and I already installed Kibana 5.1.1 on my machine. I'm trying to install Sense using the following command:
`D:\kibana-5.1.1-windows-x86\bin> kibana-plugin.bat install elastic/sense`
and I'm getting the following error messages:

> Attempting to transfer from elastic/sense
> Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/elastic/sense/elastic/sense-5.1.1.zip
> Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by johtani** [comment]
Hi @ashrav ,
"Sense is now included as Console in Kibana 5.0. "
Please see details https://github.com/elastic/sense/blob/master/README.md .

**Comment by yuganghu** [comment]
I got the same error message. 
/app/sense returns:
{"statusCode":404,"error":"Not Found","message":"Unknown app sense"}

**Comment by fwhezfwhez** [comment]
哈哈，试试能不能说中文
Kibana  has Sense part as Dev tools - console
