### ISSUE TITLE
Sense fails with SSL (using own RootCA)

### ISSUE THREAD

**Issue by nellicus** [elastic/sense#69]
Using 4.2 kibana snapshot with config

```
abonuccelli@w530 /opt/elk/PRODSEC/kibana/kibana-4.2.0-snapshot-linux-x64 $ egrep '^[^#]' config/kibana.yml 
server.host: "0.0.0.0"
elasticsearch.url: "https://localhost:9200"
elasticsearch.username: kibana_server_user
elasticsearch.password: r1ng3r
elasticsearch.ssl.ca: /opt/elk/PRODSEC/FS/secure/cacert.pem
elasticsearch.ssl.verify: true
logging.verbose: true
```

RootCa cert
```
abonuccelli@w530 /opt/elk/PRODSEC/kibana/kibana-4.2.0-snapshot-linux-x64 $ openssl x509 -in /opt/elk/PRODSEC/FS/secure/cacert.pem -inform pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 18411508252604821347 (0xff82d13517aeef63)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN="Tony-Secure-CA"
        Validity
            Not Before: Sep 29 11:11:46 2015 GMT
            Not After : Sep 26 11:11:46 2025 GMT
        Subject: CN="Tony-Secure-CA"
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c9:10:af:e5:f4:30:5f:78:b8:7c:ec:a8:3c:ac:
                    bb:4f:c8:d8:ef:83:1d:44:15:7a:80:a6:c4:e9:b2:
                    59:bb:0f:3e:26:d8:32:8a:48:ce:f7:60:28:a4:b2:
                    e2:55:23:e8:36:1c:a1:ac:6f:33:9f:8a:34:c2:af:
                    f1:cb:d1:6d:a7:f9:3d:05:68:f3:68:cc:d1:ca:db:
                    af:3d:5f:a5:73:d8:03:5f:39:65:b0:cc:4d:54:43:
                    af:1e:66:23:6f:9b:29:ba:2b:4d:a9:b8:85:73:f9:
                    b1:8c:ea:62:d9:8a:18:15:b4:7d:f5:71:48:c5:60:
                    5e:ac:b6:6c:a7:e7:3f:93:82:22:5b:21:52:f5:3c:
                    e6:c5:d4:ff:55:f7:2a:19:3c:d4:c2:b8:04:3d:4d:
                    e7:1c:64:c7:a4:3d:28:1d:2f:82:d0:62:4b:4a:02:
                    71:80:26:f9:20:de:5e:7c:9b:b0:f4:e9:f8:21:e9:
                    44:7a:62:bb:33:cb:0e:50:a8:70:23:34:10:7d:ac:
                    ca:0a:0f:7e:86:53:ec:97:99:ad:c8:08:ed:ca:d0:
                    68:03:8b:a3:bc:f6:de:da:4a:8a:de:34:70:fa:6c:
                    a1:eb:50:37:b1:1f:5b:bc:80:a0:60:21:94:1e:9a:
                    7d:f8:a2:f4:67:c2:5c:ee:d8:fb:15:84:1b:0c:3b:
                    06:db
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Subject Key Identifier: 
                CE:F3:A7:6E:CC:1A:F2:1E:D5:41:9C:00:48:DC:2B:4C:6C:98:8C:33
            X509v3 Authority Key Identifier: 
                keyid:CE:F3:A7:6E:CC:1A:F2:1E:D5:41:9C:00:48:DC:2B:4C:6C:98:8C:33
                DirName:/CN="Tony-Secure-CA"
                serial:FF:82:D1:35:17:AE:EF:63

    Signature Algorithm: sha256WithRSAEncryption
         8f:bd:46:55:dd:c4:4a:9f:d3:a7:47:78:7d:40:50:59:99:d3:
         08:cf:0c:e9:dc:14:89:6e:5b:34:de:63:d8:84:9c:78:95:a5:
         a7:3c:5d:93:90:ea:f6:72:ed:a3:1e:59:7a:d9:7b:36:a2:2a:
         d4:1b:bc:a1:d6:4f:be:44:5a:cd:50:7a:ae:77:30:69:80:54:
         61:09:c7:5e:d2:08:71:ed:d1:6a:42:87:ae:b4:fb:35:24:d9:
         97:dd:a8:44:2a:79:3a:d4:b8:e1:8f:39:25:8a:7e:8b:bd:a9:
         88:24:2e:0d:88:4a:3d:ef:dd:9f:e6:7c:f2:aa:17:9a:c9:c1:
         d3:09:1b:50:8f:f3:3f:fc:fe:a6:c1:5c:56:4f:62:f3:00:7e:
         bc:48:37:4c:ac:a3:8f:30:d7:9e:bb:91:c2:52:69:f0:8f:da:
         27:78:b2:b2:34:60:7c:1f:54:d3:0e:35:0f:a5:fa:73:d1:f4:
         65:9a:ed:a0:bf:fa:65:b1:43:9f:96:e8:91:dc:14:35:11:46:
         7e:02:e1:03:66:7b:06:82:c9:56:52:8e:04:7f:e1:45:48:73:
         05:1d:c5:81:34:d0:96:ed:e7:a3:e9:76:10:e1:f5:f0:c2:d5:
         0e:aa:0a:db:66:82:79:b9:58:ce:3e:c0:3d:42:e0:8f:14:7d:
         85:b2:46:ee
```
generated as per https://www.elastic.co/guide/en/shield/current/certificate-authority.html

**Comment by bleskes** [comment]
@spalger does it make sense to add these SSL config options to the Sense proxy?

**Comment by spalger** [comment]
Yeah, it's tricky to say because those ssl parameters are only useful for a subset of the possible servers the proxy will connect to. Used in tandom with the proxyFilter setting it makes some more sense, but then we need to ssl settings for different domains (which seems gross).

Maybe we should try to find a way to learn if the server's ssl is not verifiable and then just show that to the user (like a browser would, maybe with a red [fa-unlock-alt](http://fortawesome.github.io/Font-Awesome/icon/unlock-alt/)).

Another option we have is to allow users to extend the root CA's that sense (or even kibana) use... This feels like the preferred option to me and is something we can implement in sense today and extend to the entire server at a later time.

**Comment by bleskes** [comment]
> Maybe we should try to find a way to learn if the server's ssl is not verifiable and then just show that to the user (like a browser would, maybe with a red fa-unlock-alt).

That's sounds promising, but I think that just the lock is too subtle (unless we have the server drop down list). Have a more prominent error/warning bar would be good, but then we need to migrate all proxy errors there. Shouldn't be too much but I'm not sure we should embark down that road where we haven't pinned down the UI changes.

>  extend the root CA's that sense

Allowing to add a custom CA sounds like a good solution to me. I'm +1 on that.

Alternatively, if that turns out complicated, we can also just add a  "allow unverified ssl" (to be named better) setting that allows to connect anyway (the equivalent to people authorizing it in the browser).

**Comment by GlenRSmith** [comment]
:+1:

**Comment by sherzberg** [comment]
Until a proper solution is implemented, are there any workarounds?

**Comment by spalger** [comment]
The only real workaround @sherzberg would be to patch the source. If you are interested in that approach you would need to patch the [proxy config](http://hapijs.com/api/8.8.1#user-content-route.config.proxy) of sense's main [proxy path](https://github.com/elastic/sense/blob/master/index.js#L54) and either tell it to use a custom [Node.js SSL Agent](https://nodejs.org/api/https.html#https_class_https_agent) or stop rejecting unauthorized requests.

**Comment by sherzberg** [comment]
@spalger thanks for some direction! I am going to try and patch this until a more appropriate fix is available.

**Comment by inqueue** [comment]
@sherzberg Until the Sense plugin is fixed, the workaround is adding `rejectUnauthorized: false` to `installedPlugins/sense/index.js`.

```
--- index.js.old	2015-12-01 19:36:46.000000000 -0500
+++ index.js	2015-12-01 17:41:14.000000000 -0500
@@ -71,6 +71,7 @@
               },
               passThrough: true,
               xforward: true,
+              rejectUnauthorized: false,
 	      onResponse: function (err, res, request, reply, settings, ttl) {
                 if (err != null) {
                   reply("Error connecting to '" + request.query.uri + "':\n\n" + err.message).type("text/plain").statusCode = 502;
```
Restart Kibana after patching.

__CAUTION__: This effectively disables certificate verification in the Sense plugin proxy handler. Use at your own risk!

**Comment by nellicus** [comment]
thanks @inqueue for that!

@spalger @bleskes is there a timeline for fixing this? this effectively prevents any use of Sense

**Comment by GlenRSmith** [comment]
Is this resolved simply by Sense being a Kibana plugin?

**Comment by jakommo** [comment]
:+1:

**Comment by allenmchan** [comment]
+1

**Comment by spalger** [comment]
I released 2.0.0-beta3 Friday, Feb 26, with support for **disabling** SSL verification via the kibana.yml configuration.

Install the latest version of sense with `bin/kibana plugin --install elastic/sense` and add the `sense.ssl.verify: false` setting to your kibana.yml file to temporarily workaround this issue.

For now I'll be keeping this issue open so that we can work for an **actual** solution at will allow properly verifying self-signed certificates without modifying the source code.

**Comment by spalger** [comment]
I'm working on a solution that will allow you to map ssl settings to hostname patterns.

**Comment by spalger** [comment]
Alright, just pushed sense 2.0.0-beta4. This version includes a new `sense.proxyConfig` configuration option that allows specifying proxy configuration based on the target of proxy requests.

The option is detailed in the [installation docs](https://www.elastic.co/guide/en/sense/current/installing.html#configuration) and in this [pull request](https://github.com/elastic/sense/pull/120).

Until the "latest" redirect is updated, install 2.0.0-beta4 explicitly by telling kibana the version number:

```sh
./bin/kibana plugin --install elasticsearch/sense/2.0.0-beta4
```

**Comment by sherzberg** [comment]
I just tried this and got this in my logs and kibana exited:

```
{"type":"log","@timestamp":"2016-03-11T17:34:40+00:00","tags":["fatal"],"pid":71,"level":"fatal","message":"child \"sense\" fails because [child \"proxyConfig\" fails because [\"proxyConfig\" at positi
on 0 fails because [\"match.protocol\" is not allowed, \"ssl.verify\" is not allowed]]]","error":{"message":"child \"sense\" fails because [child \"proxyConfig\" fails because [\"proxyConfig\" at position 0 fails
 because [\"match.protocol\" is not allowed, \"ssl.verify\" is not allowed]]]","name":"ValidationError","stack":"ValidationError: child \"sense\" fails because [child \"proxyConfig\" fails because [\"proxyConfig\
" at position 0 fails because [\"match.protocol\" is not allowed, \"ssl.verify\" is not allowed]]]\n    at Object.exports.process (/opt/kibana/node_modules/joi/lib/errors.js:140:17)\n    at [object Object].intern
als.Any._validateWithOptions (/opt/kibana/node_modules/joi/lib/any.js:649:25)\n    at [object Object].root.validate (/opt/kibana/node_modules/joi/lib/index.js:102:23)\n    at Config._commit (/opt/kibana/src/serve
r/config/Config.js:134:25)\n    at Config.set (/opt/kibana/src/server/config/Config.js:104:12)\n    at Config.extendSchema (/opt/kibana/src/server/config/Config.js:69:14)\n    at ScopedPlugin.readConfig$ (/opt/ki
bana/src/server/plugins/Plugin.js:68:20)\n    at tryCatch (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:67:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/kibana/node_modules/bab
el-runtime/regenerator/runtime.js:315:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)\n    at GeneratorFuncti
onPrototype.invoke (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:136:37)\n    at run (/opt/kibana/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47)\n    at /opt/kibana/n
ode_modules/babel-core/node_modules/core-js/modules/es6.promise.js:115:28\n    at flush (/opt/kibana/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:19:5)\n    at nextTickCallbackWith0Args (no
de.js:415:9)\n    at process._tickDomainCallback (node.js:385:13)"}}
FATAL { [ValidationError: child "sense" fails because [child "proxyConfig" fails because ["proxyConfig" at position 0 fails because ["match.protocol" is not allowed, "ssl.verify" is not allowed]]]]
...
```

Here is my sense configuration in kibana.yml:

```
sense.proxyConfig:                                                                                                                                                                                            
  - match.protocol: "https"
    ssl.verify: false
```

What am I missing?

**Comment by sherzberg** [comment]
Sorry, I should be more clear, i tried the `beta4` in my last post. So `beta4` is not working for me.

`beta3` seems to work fine with just `sense.ssl.verify: false`.

**Comment by spalger** [comment]
@sherzberg sorry, I wrote the docs wrong. Until https://github.com/elastic/kibana/issues/6518 is fixed properties within the proxyConfig list can't use dot-separated key names.

Updated the [docs in the repo](https://github.com/elastic/sense/blob/master/docs/installing_sense.asciidoc#configuration) and they should be updated on elastic.co soon (once CI runs).

**Comment by spalger** [comment]
Note to anyone following along, beta4 only allowed GET requests to be proxied. Just released beta5 which fixes this. Updated https://github.com/elastic/sense/issues/69#issuecomment-195231695 as well.

```sh
./bin/kibana plugin --install elasticsearch/sense/2.0.0-beta5
```

**Comment by sherzberg** [comment]
@spalger Awesome, thanks for the quick response! The non-dotted paths worked fine on beta5.

**Comment by yt449** [comment]
Tried to install sense, however got the message:

Installing sense
Attempting to transfer from https://download.elastic.co/elasticsearch/sense/sense-2.0.0-beta5.tar.gz
Error: Client request error: self signed certificate in certificate chain
Plugin installation was unsuccessful due to error "Client request error: self signed certificate in certificate chain"
