### ISSUE TITLE
Sense result pane only shows 14 lines on IE 11

### ISSUE THREAD

**Issue by LeeDr** [elastic/sense#70]
Using Kibana 4.2.0-snapshot on Windows 10.
I installed sense, restarted Kibana, opened sense in IE 11, ran the default query, the results came back but only shows lines 1 - 14.  I can scroll down on the right pane and see more results but the lower 3/4 of the pane stays blank (see screenshot).

But once I resize the IE just slightly, the right pane repainted and showed all lines correctly.  Running the query again shows all result lines correctly.  So in my case it was just a problem on the first opening of the sense page.

I closed IE and reopened it, went to sense, ran the query, it worked fine.  I'm not sure if I could reproduce it at this point.  It could be an issue with my UHD video driver on my ASUS laptop.

Seems to work fine on Microsoft Edge browser.
![sense1](https://cloud.githubusercontent.com/assets/13542669/10790474/81cc1dca-7d51-11e5-911b-2800547cff6c.PNG)
![sense2](https://cloud.githubusercontent.com/assets/13542669/10790484/8f5aa8a8-7d51-11e5-986e-ff9f623eec75.PNG)

Here's the output of me installing sense;
```
C:\kibana-4.2.0-snapshot-windows\kibana-4.2.0-snapshot-windows\bin>kibana.bat plugin -i elastic/sense
Installing sense
Attempting to extract from https://download.elastic.co/elastic/sense/sense-latest.tar.gz
Downloading 318236 bytes....................
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete

C:\kibana-4.2.0-snapshot-windows\kibana-4.2.0-snapshot-windows\bin>
```

**Comment by spalger** [comment]
@LeeDr sometimes this is cause by a race condition I need to track down in the re-rendering code. Can you try resizing the window and see if things look better afterwards?

**Comment by spalger** [comment]
Ah, I see that you already answered that in the description
