### ISSUE TITLE
Sense now has weird ES dependencies based upon Kibana

### ISSUE THREAD

**Issue by eskibars** [elastic/sense#77]
You have to have a local ES instance running in order to access Sense at all, which seems like a weird requirement given its current focus as a (much, much smarter) "cURL replacement".

1. Start Kibana (but don't start ES)
2. Navigate to the Sense app

You get the Kibana cluster status page only being red.  This makes it impossible to, for example, use Sense locally against only a remote cluster (without also having a local instance running)

**Comment by kjbekkelund** [comment]
This would be nice for Found to have too (as we also don't depend on the underlying ES, we just want the Kibana chrome). Don't know if it's possible with Kibana apps today? (I couldn't get it to work when I tried)

**Comment by bleskes** [comment]
@eskibars  see https://www.elastic.co/guide/en/sense/current/installing.html#disable_discover . I think this what you're looking for.

@kjbekkelund I'm not sure I follow you. if the above link is not what you need, please ping and we'll figure things out..

**Comment by kjbekkelund** [comment]
Ah, it seems to be a bug in Kibana related to routing on the frontend when certain things are turned off. But yeah, got our app running without Elasticsearch now :+1:

**Comment by eskibars** [comment]
Thanks @bleskes: I missed that.  Will close.
