### ISSUE TITLE
View in Sense is no longer working

### ISSUE THREAD

**Issue by clintongormley** [elastic/sense#87]
The View in Sense buttons in the docs no longer work.  There were issues with the website itself (see https://github.com/elastic/website-www.elastic.co/issues/744) but these have been resolved.  Now I think the issue is with Sense/Kibana.

When trying to load this URL: http://localhost:5601/app/sense?load_from=http://www.elastic.co/guide/en/elasticsearch/reference/current/snippets/copy-to/1.json

I get this in the console:

    unable to load ace/lib/es5-shim
    sense?load_from=http://www.elastic.co/guide/en/elasticsearch/reference/current/snippets/copy-to/1.j…:1 XMLHttpRequest cannot load http://www.elastic.co/guide/en/elasticsearch/reference/current/snippets/copy-to/1.json. 
    Request header field kbn-xsrf-token is not allowed by Access-Control-Allow-Headers in preflight response.

So first the JSON snippet doesn't load.  But then there is a second issue caused (I think) by the `?load_from...` query string.  If I try to run a command in Sense, I get:

    Uncaught TypeError: Cannot read property 'indexOf' of undefined (http://localhost:5601/bundles/sense.bundle.js:28371)
    Version: 4.3.0-snapshot
    Build: 9367
    Error: Uncaught TypeError: Cannot read property 'indexOf' of undefined (http://localhost:5601/bundles/sense.bundle.js:28371)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js:64531:25)

**Comment by spalger** [comment]
@clintongormley is this something we can fix on our end until we can patch sense? If we add `kbn-xsrf-token` to the `Access-Control-Allow-Headers` response then things should start working again.

**Comment by beardedlinuxgeek** [comment]
The current issue appears to be a redirect loop on the elastic.co website.

**Comment by clintongormley** [comment]
No, it's that Kibana has added a `kbn-version` header... which has broken View in Sense again.

**Comment by clintongormley** [comment]
This has been fixed
