### ISSUE TITLE
Installation of sense fails with "Cannot find module 'joi'"

### ISSUE THREAD

**Issue by mrueegg** [elastic/sense#93]
Hi,

When I attempt to install sense through

$ kibana plugin --install elastic/sense

it fails with the message

Installing sense
Attempting to extract from https://download.elastic.co/elastic/sense/sense-latest.tar.gz
Downloading 318236 bytes....................
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Cannot find module 'joi'"

Note that I have installed joi globally with

$ npm install -g joi

but this doesn't help. Any ideas? Thanks in advance.

**Comment by spalger** [comment]
How did you install Kibana?

**Comment by mrueegg** [comment]
With homebrew (brew install kibana):

$ brew info kibana
kibana: stable 4.3.1 (bottled), HEAD
Analytics and search dashboard for Elasticsearch
https://www.elastic.co/products/kibana
/usr/local/Cellar/kibana/4.1.1 (3,672 files, 23.3M)
  Poured from bottle
/usr/local/Cellar/kibana/4.3.1 (13,686 files, 106.6M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/kibana.rb
==> Caveats
Plugins: /usr/local/var/kibana/installedPlugins/
Config: /usr/local/etc/kibana/

**Comment by spalger** [comment]
Hmm, my guess is that since the homebrew installer puts different parts in different places it breaks the plugin installer. We don't support installing from brew though, but installing kibana is as easy as extracting an archive and running a command: https://www.elastic.co/downloads/kibana

**Comment by mrueegg** [comment]
Thanks, the version from the homepage worked like a charm.

**Comment by AndersonZacharyT** [comment]
After installing Kibana through the Homepage version, I'm still having the module 'joi' not be found when I try to install Sense. I'm using the command:
    
    kibana plugin --install elastic/sense

**Comment by spalger** [comment]
@AndersonZacharyT can you verify that you're using the right kibana install?

```
which kibana
```

**Comment by AndersonZacharyT** [comment]
Thanks for getting back to me. It's Kibana version 4.3.1

**Comment by spalger** [comment]
I'm actually concerned that you might still be (accidentally) running the brew installed version of kibana. Did you uninstall it with `brew uninstall kibana`?
